name: Java CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        cache: 'gradle'
    - name: Build mod jar
      run: ./gradlew deploy
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/libs/${{ github.event.repository.name }}.jar
